# Generated by Django 4.1.7 on 2023-07-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_color_alter_product_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
