# Generated by Django 4.1.7 on 2023-07-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='added',
            field=models.DateField(default='2022-02-02'),
            preserve_default=False,
        ),
    ]
